[package]
name = "zk-halo2"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "benchmarking",
    "residue_pattern", "fib",
]

[dependencies]
residue_pattern = { version = "^0.1.0", path = "./residue_pattern" }
fib = { version = "^0.1.0", path = "./fib" }


